const AboutData = [
  {
    id: 1,
    title: "Our Story",
    description:
      "We are a team of passionate storytellers who love to create and share stories with the world. We believe that stories have the power to inspire, entertain, and connect people across cultures and generations. That’s why we created Picstone, an app that lets you generate stories based on any image you upload.",
    imgLink:
      "https://res.cloudinary.com/dixoiunbw/image/upload/v1697473058/picstone/about-page/czfex3i33uf641jwgont.jpg",
  },
  {
    id: 2,
    title: "Our Vision",
    description:
      "Our vision is to make storytelling accessible and fun for everyone. Whether you want to write a novel, a short story, a blog post, or a social media caption, Picstone can help you unleash your creativity and find your voice. You can choose from different themes, genres, and styles to suit your mood and preference. You can also edit and customize your stories as much as you want.",
    imgLink:
      "https://res.cloudinary.com/dixoiunbw/image/upload/v1697473090/picstone/about-page/ejcs5pbxsirvq6mbfimn.jpg",
  },
  {
    id: 3,
    title: "Our Platform",
    description:
      "Picstone is powered by artificial intelligence that analyzes your image and generates a story based on it. The app uses natural language processing and computer vision to understand the context, emotions, and details of your image. The app also learns from your feedback and preferences to improve the quality and diversity of the stories.",
    imgLink:
      "https://res.cloudinary.com/dixoiunbw/image/upload/v1697474577/picstone/about-page/kgnw7ekf1pabxfau9zvs.jpg",
  },
  {
    id: 4,
    title: "Our Commitment",
    description:
      "We are committed to providing you with a safe, secure, and enjoyable experience with Picstone. We respect your privacy and do not store or share your images or stories without your consent. We also monitor and moderate the content generated by the app to ensure that it is appropriate and respectful. We welcome your suggestions and feedback to help us improve our app and service.",
    imgLink:
      "https://res.cloudinary.com/dixoiunbw/image/upload/v1697474565/picstone/about-page/c3zzjmbmyeleqpyhktnn.jpg",
  },
];

export default AboutData;
